file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Ching/.gitconfig	user.name=Chingiz
file:C:/Users/Ching/.gitconfig	user.email=taibovchingiz@gmail.com
file:C:/Users/Ching/.gitconfig	core.autocrlf=true
file:C:/Users/Ching/.gitconfig	core.safecrlf=warn
file:C:/Users/Ching/.gitconfig	core.safectlf=warn
file:C:/Users/Ching/.gitconfig	alias.co=checkout
file:C:/Users/Ching/.gitconfig	alias.ci=commit
file:C:/Users/Ching/.gitconfig	alias.st=status
file:C:/Users/Ching/.gitconfig	alias.br=branch
file:C:/Users/Ching/.gitconfig	alias.hist=log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short
file:C:/Users/Ching/.gitconfig	alias.type=cat-file -t
file:C:/Users/Ching/.gitconfig	alias.dump=cat-file -p
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/ChiNiz/kursovayamebel.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
